LeisureStar/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LeisureStar.Models;
using ExoModel;

namespace LeisureStar.Controllers
{
	public class GameController : Controller
	{
		/// <summary>
		/// /Game
		/// </summary>
		/// <returns></returns>
		public ActionResult Index()
		{
			ViewBag.Title = "Games";
			return View(Game.All);
		}

		[AllowAnonymous]
		public ActionResult Edit(string id)
		{
			ViewBag.Title = "Edit Game";
			return View(ModelContext.Create<Game>(id));
		}

		[AllowAnonymous]
		public ActionResult ViewResults(string id)
		{
			ViewBag.Title = "Game Results";
			return View(ModelContext.Create<Game>(id));
		}

		[AllowAnonymous]
		public ActionResult Play(string id)
		{
			ViewBag.Title = "Play Game";
			return View(ModelContext.Create<Game>(id));
		}

	}
}

LeisureStar/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LeisureStar.Models;
using ExoModel;

namespace LeisureStar.Controllers
{
	public class PlayerController : Controller
	{
		/// <summary>
		/// /Player
		/// </summary>
		/// <returns></returns>
		public ActionResult Index()
		{
			ViewBag.Title = "Players";
			return View(Player.All);
		}

		/// <summary>
		/// /Player/Edit/#
		/// </summary>
		/// <param name="id"></param>
		/// <returns></returns>
		public ActionResult Edit(string id)
		{
			ViewBag.Title = "Edit Player";
			return View(ModelContext.Create<Player>(id));
		}
	}
}

LeisureStar/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LeisureStar.Models;
using ExoModel;

namespace LeisureStar.Controllers
{
	public class TeamController : Controller
	{
		/// <summary>
		/// /Team
		/// </summary>
		/// <returns></returns>
		public ActionResult Index()
		{
			ViewBag.Title = "Teams";
			return View(Team.All);
		}

		/// <summary>
		/// /Team/Edit/#
		/// </summary>
		/// <param name="id"></param>
		/// <returns></returns>
		public ActionResult Edit(string id)
		{
			ViewBag.Title = "Edit Team";
			return View(ModelContext.Create<Team>(id));
		}
	}
}

LeisureStar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title</title>
	<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/jquery-1.4.2.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/Ajax/MicrosoftAjax.debug.js?cachehash=" + ExoWeb.CacheHash)" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/Ajax/MicrosoftAjaxTemplates.debug.js?cachehash=" + ExoWeb.CacheHash)" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/ExoWeb/exoweb-msajax.js?cachehash=" + ExoWeb.CacheHash)" type="text/javascript"></script>

	<script>
		$(function () {
			function createDatePicker() {
				$(this).datepicker({
					minDate: new Date('1/1/0001'),
					maxDate: new Date('12/31/9999'),
					yearRange: '-110:+50',
					duration: 0,
					dateFormat: 'm/d/yy',
					showOn: 'button',
					changeYear: true,
					changeMonth: true,
					onSelect: function (val, control) {
						// jquery trigger doesn't seem to raise the event
						// properly, so raise it here
						var el = $(this).get(0);
						if (el.fireEvent) { el.fireEvent("onchange"); }
						else if (el.dispatchEvent) {
							var evt = document.createEvent("MutationEvents");
							evt.initEvent("change", false, true);
							el.dispatchEvent(evt);
						}
					}
				});
			}

			$("input.datepicker:bound").ever(createDatePicker);
		});
	</script>
	
	<!-- Add default validation display -->
	<script type="text/javascript">

		ExoWeb.config.debug = true;

		function setState(el, prefix, current, all) {
			all.forEach(function (state) {
				if (current === state)
					el.addClass(prefix + "-" + state);
				else
					el.removeClass(prefix + "-" + state);
			});
		}

		$("input:bound, select:bound, textarea:bound").ever(function () {
			$(this).validated(function (sender, issues) {

				// locate validation area
				var $area = $(this).closest(".field");
				var $validation = $area.find(".validation");

				if ($validation.size() == 0) {
					$validation = $(this).next();

					if (!$validation.is('.validation')) {
						// container not found so inject it
						$validation = $(this).after("<div class='validation'></div>").next();
					}
				}

				var states = ["some", "none"];

				if (issues.length == 0) {
					setState($(this), "validated", "none", states);
					setState($validation, "validation", "none", states);
					setState($area, "validated", "none", states);
				} else {
					setState($(this), "validated", "some", states);
					setState($validation, "validation", "some", states);
					setState($area, "validated", "some", states);

					$validation.text(issues[0].get_message());
				}
			});
		});
		@RenderSection("startupScript", required: false)
	</script>
</head>
<body xmlns:sys="javascript:Sys" 
		xmlns:dataview="javascript:Sys.UI.DataView" 
		xmlns:field="javascript:ExoWeb.UI.Field" 
		xmlns:content="javascript:ExoWeb.UI.Content" 
		xmlns:template="javascript:ExoWeb.UI.Template"
		xmlns:toggle="javascript:ExoWeb.UI.Toggle"
		sys:activate="*">
	<div class="page">
		<header>
			<div id="title">
				<h1>LeisureStar</h1>
			</div>
			<div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
			<nav>
				@if (Request.IsAuthenticated)
				{
					<ul id="menu">
						<li>@Html.ActionLink("Home", "Index", "Home")</li>
						<li>@Html.ActionLink("Players", "Index", "Player")</li>
						<li>@Html.ActionLink("Teams", "Index", "Team")</li>
						<li>@Html.ActionLink("Games", "Index", "Game")</li>
					</ul>
				}
			</nav>
		</header>
		<section id="main">
			<h2>@ViewBag.Title</h2>
			@RenderBody()
		</section>
		<footer>
		</footer>
	</div>
</body>
</html>

LeisureStar/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}